let tripsData = [
    {
        id: 1, 
        imgSrc: '/Image/TripSort_Greece Tour.jpg', 
        name: 'Greece Tour', 
        location: 'Paris', 
        length: 8, 
        saleAmount: '8%', 
        numberPrice: 1200 , 
        actualPrice: '1,200', 
        strikedPrice: '1,300.00',
        activities: 'Hiking',
        triptypes: 'Homestay'
    },
    {
        id: 2, 
        imgSrc: '/Image/TripSort_Best Tour Of The Year.jpg', 
        name: 'Best Tour Of The Year', 
        location: 'Bhutan', 
        length: 16, 
        saleAmount: '23%', 
        numberPrice: 1500 , 
        actualPrice: '1,500', 
        strikedPrice: '1,950.00',
        activities: 'Kayaking',
        triptypes: 'Cultural'
    },
    {
        id: 3, 
        imgSrc: '/Image/TripSort_Rocky Mountain Vacations.jpg', 
        name: 'Rocky Mountain Vacations', 
        location: 'Nepal', 
        length: 13, 
        saleAmount: '30%', 
        numberPrice: 1400 , 
        actualPrice: '1,400', 
        strikedPrice: '1,000.00',
        activities: 'Paragliding',
        triptypes: 'Natural Walk'
    },
    {
        id: 4, 
        imgSrc: '/Image/TripSort_Dolpo Trekking.jpg', 
        name: 'Dolpo Trekking', 
        location: 'Nepal', 
        length: 17, 
        saleAmount: '15%', 
        numberPrice: 1100 , 
        actualPrice: '1,100', 
        strikedPrice: '1,300.00',
        activities: '',
        triptypes: ''
    },
    {
        id: 5, 
        imgSrc: '/Image/TripSort_Kathmandu Chitwan Tour.jpg', 
        name: 'Kathmandu Chitwan Tour', 
        location: 'Nepal', 
        length: 7, 
        saleAmount: '28%', 
        numberPrice: 1300 , 
        actualPrice: '1,300', 
        strikedPrice: '1,800.00',
        activities: '',
        triptypes: ''
    },
    {
        id: 6, 
        imgSrc: '/Image/TripSort_Langtang Trek.jpg', 
        name: 'Langtang Trek', 
        location: 'Nepal', 
        length: 13, 
        saleAmount: '17%', 
        numberPrice: 1000 , 
        actualPrice: '1,000', 
        strikedPrice: '1,199.00',
        activities: '',
        triptypes: ''
    },
    {
        id: 7, 
        imgSrc: '/Image/TripSort_Chulu Peak Climbing.jpg', 
        name: 'Chulu Peak Climbing', 
        location: 'Nepal', 
        length: 10, 
        saleAmount: '13%', 
        numberPrice: 1700 , 
        actualPrice: '1,700', 
        strikedPrice: '1,950.00',
        activities: '',
        triptypes: ''
    },
    {
        id: 8, 
        imgSrc: '/Image/TripSort_Tilicho Lake Trek.jpg', 
        name: 'Tilicho Lake Trek', 
        location: 'Nepal', 
        length: 11, 
        saleAmount: '12%', 
        numberPrice: 1500 , 
        actualPrice: '1,500', 
        strikedPrice: '1,700.00',
        activities: '',
        triptypes: ''
    },
    {
        id: 9, 
        imgSrc: '/Image/TripSort_Upper Mustang Trek.jpg', 
        name: 'Upper Mustang Trek', 
        location: 'Nepal', 
        length: 16, 
        saleAmount: '15%', 
        numberPrice: 1700 , 
        actualPrice: '1,700', 
        strikedPrice: '2,000.00',
        activities: '',
        triptypes: ''
    },
    {
        id: 10, 
        imgSrc: '/Image/TripSort_Paragliding is Life.jpg', 
        name: 'Paragliding is Life', 
        location: 'Nepal', 
        length: 15, 
        saleAmount: '10%', 
        numberPrice: 1800 , 
        actualPrice: '1,800', 
        strikedPrice: '2,000.00',
        activities: '',
        triptypes: ''
    },
]